[tool.poetry]
name = "xenray"
version = "1.0.0"
description = "An Xray GUI for Linux/Windows, focusing on simplicity and enhancing VPN experience"
authors = ["Xenups"]
license = "AGPL-3.0-or-later"
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
flet = "^0.24.0"
requests = "^2.31.0"
psutil = "^5.9.0"
loguru = "^0.7.3"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"
mypy = "^1.5.0"

[tool.poetry.scripts]
xenray = "src.main:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
